feat(auth): 管理者用の認証機能を実装 (#2)

diff --git a/.github/workflows/ci-for-all.yaml b/.github/workflows/ci-for-all.yaml
--- a/.github/workflows/ci-for-all.yaml
+++ b/.github/workflows/ci-for-all.yaml
@@ -3,6 +3,11 @@ on:
   push:
 
 env:
+  TZ: 'Asia/Tokyo'
+  DB_HOST: 127.0.0.1
+  DB_PORT: 3306
+  DB_USERNAME: root
+  DB_PASSWORD: 12345678
   GO_VERSION: 1.21.0
 
 jobs:
@@ -144,6 +149,26 @@ jobs:
       uses: actions/setup-go@v4
       with:
         go-version: ${{ env.GO_VERSION }}
+
+    - name: Start MySQL container
+      working-directory: .
+      run: docker compose --file=docker-compose.ci.yaml up --build --detach mysql
+
+    - name: Wait start MySQL
+      run: |
+        #!/bin/bash
+        retry=60
+        count=1
+        until mysqladmin ping -h${DB_HOST} -P${DB_PORT} -u${DB_USERNAME} -p${DB_PASSWORD}; do
+          echo 'mysql is unavailable - sleeping'
+          sleep 3
+          if [ $(expr $retry - $count) -le 0 ]; then
+            echo 'mysql is unavailable - throw error for timeout'
+            exit 1
+          fi
+          count=$(expr $count + 1)
+        done
+        echo 'mysql is up - executing command'
 
     - name: Setup
       run: make setup
